### ISSUE TITLE
Rare occurrences of NullPointerException in DiscreteEventSimulator

### ISSUE THREAD

**Issue by ngyewch** [org-arl/fjage#107]
Issue encountered in version: 1.6.2

Reproducibility: low

## Sample error
```
Jan 01, 1970 8:31:23 AM org.arl.fjage.DiscreteEventSimulator run
SEVERE: Exception: 
java.lang.NullPointerException
	at org.arl.fjage.DiscreteEventSimulator.run(DiscreteEventSimulator.java:144)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mchitre** [comment]
@ngyewch do you have details of the simulation you were running when you encountered this?

**Comment by ngyewch** [comment]
The test involves having an existing simulator shut down, and starting another simulator afterwards to approximate a restart scenario I have only encountered that issue in a test case with that behavior.

Reviewing the code again, this is likely caused by the simulator shutdown. Most likely culprit is `events.clear()` in `DiscreteEventSimulator.shutdown()`.

**Comment by mchitre** [comment]
Should be fixed. Hard to consistently reproduce and so to cross-check. Reopen if anyone sees this again.
