### ISSUE TITLE
Bad Json error for GenericMessage with inReplyTo as null

### ISSUE THREAD

**Issue by AnneThKu** [org-arl/fjage#110]
When a GenericMessage is sent with performative as REQUEST, a Bad JSON error is shown in the logs as below.
```
1579079595745 | WARNING | org.arl.fjage.remote.ConnectionHandler@20:run | Bad JSON request: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was NULL at line 1 column 224 path $.message.data.inReplyTo in {"action":"send","relay":true,"message":{ "clazz": "org.arl.fjage.GenericMessage", "data": {"msgID":"3c5d13ceb013081a0e653a4b15782da3","sender":"WebGW-bd2cc5362fae94f3","recipient":"europa","perf":"REQUEST","inReplyTo":null,"divestart":false,"diveNo":"Dive_0001"} }}
-- | -- | -- | --
```

**Comment by notthetup** [comment]
It’s unhappy with the `null` in the JSON for `inReplyTo` field . 

I believe we can fix this in the Gateway code to remove any fields that have a value of `null`. That will help to compress the JSON size too.

**Comment by mchitre** [comment]
Fixed by ensuring that the `MessageAdapterFactory` explicitly checks for nulls, and leaves those fields unset while deserializing.
