### ISSUE TITLE
Javascript API documentation page shows not found

### ISSUE THREAD

**Issue by AnneThKu** [org-arl/fjage#114]
In the fjage documentation for javascript gateway (https://fjage.readthedocs.io/en/latest/jsgw.html), there is a link to http://org-arl.github.io/fjage/jsdoc/.
But this link http://org-arl.github.io/fjage/jsdoc/  when opened shows`404- Not Found`.

**Comment by mchitre** [comment]
@notthetup We should someday consider having a Javascript API docs. Non critical for now, and I've removed the link. So the "bug" is gone :-)
