### ISSUE TITLE
Add sent timestamp in Message

### ISSUE THREAD

**Issue by ngyewch** [org-arl/fjage#117]
Add a field in Message indicating when it was sent. Preferably set during `Agent.send()`. This is useful for cases where messages can take a long time to arrive at its destination.

Suggested:
```
    /**
     * Gets the timestamp (milliseconds since epoch) that this message was sent at.
     *
     * @return The sent at timestamp.
     */
    public long getSentAt();
```

**Comment by mchitre** [comment]
Poll!

Message creation timestamp or sent-at timestamp more valuable? I want to avoid both to keep the serialized versions compact, unless there is a strong use case.

**Comment by notthetup** [comment]
Can the `sent-at timestamp` be annotated to be not serialized? I'm guessing the use-case will be mostly for bookkeeping on the sender's side.

**Comment by ngyewch** [comment]
@notthetup This came up mostly because of DTN and dynamic routing. In these situations, it's possible that messages arrive much later, or out of order.

One use case: sensor data, it would be very good to know when the data was collected.

**Comment by notthetup** [comment]
OK. So we want to know this timestamp on relay or at the receiver. So we’ll need to serialise it.

**Comment by mchitre** [comment]
Implemented as `sentAt` timestamp.
