### ISSUE TITLE
Window support for fjåge C Gateway

### ISSUE THREAD

**Issue by notthetup** [org-arl/fjage#120]
Migrating from Unet issue.

notthetup commented on 14 Oct 2019
https://github.com/DFHack/clsocket

notthetup commented on 14 Oct 2019
https://stackoverflow.com/a/28031039/577563

notthetup commented on 10 Jan • 
Winsock doesn't support poll , they have a WSAPoll which is totally broken (https://daniel.haxx.se/blog/2012/10/10/wsapoll-is-broken/) and they have select . I guess we can move to select.

We use a named pipe to break the select as a means to avoid using threads. But windows doesn't support named pipes. They have pipes but select doesn't work on those. 😞 Maybe we can move to having using tcp sockets instead of named pipes to wake up the select on both windoze and posix.

**Comment by notthetup** [comment]
notthetup commented on 10 Jan • 
Agreed that first we'll move to Sockets and select, then make it work on Windows

- [ ] ~Move to TCP Sockets instead of named pipes for self-interrupts - @mchitre ~
- [x] Move to select instead of poll - @mchitre 
- [ ] Make it work on windows - @notthetup

**Comment by notthetup** [comment]
mchitre commented 13 days ago • 
Implemented options to use poll(), select() or ioctl() for this. Option controlled via a #define in the fjage.c file: USE_POLL, USE_SELECT or USE_IOCTL. Pick your poison depending on what is easiest to work with in Windows (I suspect USE_SELECT).

Over to you @notthetup! 😬

**Comment by mchitre** [comment]
Implemented and tested in 85ebef1abec7cb644b9bc958fe27c8a510da259d. Merged to `dev`.
