### ISSUE TITLE
fjage.js should support message class inheritance

### ISSUE THREAD

**Issue by mchitre** [org-arl/fjage#121]
Would be nice to be able to define parent like in Python:
```
RxFrameNtf = MessageClass("org.arl.unet.phy.RxFrameNtf", DatagramNtf)
```

**Comment by notthetup** [comment]
https://github.com/org-arl/fjage/tree/fjagejs-inheritance

![Screenshot 2020-02-22 at 9 38 01 PM](https://user-images.githubusercontent.com/553140/75093334-a3964100-55bb-11ea-84dc-756aa43dc5d0.png)

**Comment by mchitre** [comment]
Looks good!

**Comment by notthetup** [comment]
Fixed in https://github.com/org-arl/fjage/pull/122
