### ISSUE TITLE
fjagepy : UnboundLocalError

### ISSUE THREAD

**Issue by notthetup** [org-arl/fjage#123]
I found this error in the logs for one of the tests I was running where the master that `fjåge.py` was trying to connect to tended to drop off the network sporadically. When that happened, and I tried to connect to the master again, `fjåge.py` seems to go into this error.

```
1581566939452|A|Traceback (most recent call last):
  File "osat.py", line 386, in run
    ptime = self.phy.time
  File "/Users/chinmay/Library/Python/3.7/lib/python/site-packages/unetpy/__init__.py", line 253, in getter
    rsp = self.request(_ParameterReq(index=self.index).get(param))
  File "/Users/chinmay/Library/Python/3.7/lib/python/site-packages/fjagepy/__init__.py", line 119, in request
    return self.owner.request(msg, timeout)
  File "/Users/chinmay/Library/Python/3.7/lib/python/site-packages/fjagepy/__init__.py", line 589, in request
    self.send(msg)
  File "/Users/chinmay/Library/Python/3.7/lib/python/site-packages/fjagepy/__init__.py", line 517, in send
    self.logger.debug(str(name[0]) + ":" + str(name[1]) + " >>> " + rq)
UnboundLocalError: local variable 'name' referenced before assignment
````

**Comment by prasadtiru** [comment]
Please review the fix added here https://github.com/org-arl/fjage/commit/4fe9205fbbb4a30c4891bd568cd212e084413486#diff-c627bda60a59f4668d6a18806fa988e2R699

**Comment by notthetup** [comment]
https://github.com/org-arl/fjage/blob/master/gateways/python/fjagepy/__init__.py#L591

For example, would this cause an error if `m._deserialize(msg)` throws an error? Because `demsg` would not be defined.

```
                        try:
                            m = Message()
                            demsg = m._deserialize(msg)
                        except Exception as e:
                            self.logger.critical("Exception: Class loading failed - " + str(e))
                        q.append(demsg)
```

**Comment by prasadtiru** [comment]
@notthetup  I used the PyCharm IDE now to go through the code and clean up, including the issue pointed out above and I have also tested it. Please check the modifications in commit 774666375d9b3fac40629519a453ab9c326db9f5

**Comment by notthetup** [comment]
That looks good!
