### ISSUE TITLE
`Detailed API description` link broken

### ISSUE THREAD

**Issue by manuignatius** [org-arl/fjage#129]
`Detailed API description` (http://org-arl.github.com/fjage/jsdoc/) from https://fjage.readthedocs.io/en/latest/jsgw.html is broken

**Comment by notthetup** [comment]
While we added JSAPI Documentation (https://org-arl.github.io/fjage/jsdoc/), we removed the link in https://github.com/org-arl/fjage/blob/master/src/sphinx/jsgw.rst
