### ISSUE TITLE
Add support for parameter get/set for all fjage gateways

### ISSUE THREAD

**Issue by manuignatius** [org-arl/fjage#130]
- [x] C
- [x] Python
- [x] JS
- [x] Julia
- [x] Java/Groovy

**Comment by notthetup** [comment]
I'd think we now need this for ALL the Gateways after fjage1.7.

**Comment by mchitre** [comment]
Agree

**Comment by mchitre** [comment]
@prasadtiru - Python
@notthetup - JS
@mchitre - C, Java, Groovy, Julia

**Comment by notthetup** [comment]
We'll also have to update the Gateway spec for this.

https://github.com/org-arl/fjage/blob/master/gateways/Gateways.md

**Comment by notthetup** [comment]
```
### `get()` :: String name, (int index) -> Object
- This get the value of a parameter on the Agent that the AgentID refers to.
- Convenience method to replace doing a ParameterReq to the Agent.
- May be implemented as a getter for a property the AgentID object, with the parameter name being the property name, and the index being the array index (for e.g. agent.property[index]), if the language supports it.

### `set()` :: String name, (int index),  -> Object
- Convenience method to replace doing a ParameterReq to the Agent.
- May be implemented as a setter for a property the AgentID object, with the parameter name being the property name, and the index being the array index (for e.g. agent.property[index] = value), if the language supports it.
```

Suggestions?

**Comment by mchitre** [comment]
Set requires value to be passed in

**Comment by prasadtiru** [comment]
Added the parameter get/set method in `fjagepy` in commit 4fe9205fbbb4a30c4891bd568cd212e084413486. An example usage is as given below:

```
from fjagepy import *
gw = Gateway('localhost', 1100)
preq = ParameterReq(recipient=websh)
websh = gw.agentForService(Services.SHELL)
preq = ParameterReq(recipient=websh)
rsp = gw.request(preq.get('org.arl.fjage.shell.ShellParam.language'))
print(rsp)
ParameterRsp:INFORM[language:Groovy]
```

Also supports pretty printing such as:
```
In [9]: websh
Out[9]:
<<< WEBSH >>>

[org.arl.fjage.shell.ShellParam]
  language = Groovy
```

**Comment by notthetup** [comment]
Ah yes.

```
### `get()` :: String name, (int index) -> Object
- This get the value of a parameter on the Agent that the AgentID refers to.
- Convenience method to replace doing a ParameterReq to the Agent.
- May be implemented as a getter for a property the AgentID object, with the parameter name being the property name, and the index being the array index (for e.g. agent.property[index]), if the language supports it.

### `set()` :: String name, (int index), Object value,  -> Object
- Convenience method to replace doing a ParameterReq to the Agent.
- May be implemented as a setter for a property the AgentID object, with the parameter name being the property name, and the index being the array index (for e.g. agent.property[index] = value), if the language supports it.
```

OK. Should it be 

1. `set() :: String name, (int index), Object value,  -> Object`
OR 
2. `set() :: String name, Object value, (int index)  -> Object`

1 is really hard to implement in many languages since most prefer optional arguments at the end. But the Java methods seem to be `set(index, value)`.

**Comment by mchitre** [comment]
2 is fine

**Comment by mchitre** [comment]
I'm thinking the `get` and `set` will be methods of `AgentID`. Makes sense?

**Comment by notthetup** [comment]
Yes. Sorry. I was in a rush and missed that part. These would be on `AgentID`. Optionally implemented as properties if the language permits.

**Comment by mchitre** [comment]
Updated gateway spec and implemented in Java/Groovy.

**Comment by mchitre** [comment]
C implemented and partially tested :-)

**Comment by notthetup** [comment]
JS Support PR-ed : https://github.com/org-arl/fjage/pull/133

**Comment by mchitre** [comment]
@notthetup You'll merge, or you want me to? Assignee is you.

**Comment by notthetup** [comment]
Waiting for review from @AnneThKu

**Comment by notthetup** [comment]
JS Support Merged.

**Comment by prasadtiru** [comment]
Added parameter support in Python and test code in 4bd2bd2ae2dc7e491e9358466329635d6c64950a

**Comment by mchitre** [comment]
Julia will be handled separately from 1.8 release, so dropping from the milestone

**Comment by mchitre** [comment]
Done for Julia
