### ISSUE TITLE
Update tests for parameters in fjåge 1.7

### ISSUE THREAD

**Issue by notthetup** [org-arl/fjage#132]
The current tests for fjåge 1.7 have a couple of issues.

- [x] Parameter tests tend to fail in Github Actions CI.
- [x] Parameter tests don't include tests for indexed parameters.

**Comment by notthetup** [comment]
Example of failure of tests : https://github.com/org-arl/fjage/runs/539259011?check_suite_focus=true

**Comment by mchitre** [comment]
Should be fixed.
