### ISSUE TITLE
Debug occasional timeouts seen during CI

### ISSUE THREAD

**Issue by mchitre** [org-arl/fjage#141]
Continued discussion from:
https://github.com/org-arl/fjage/pull/138#issuecomment-637961225

@ngyewch @notthetup FYI, I've created an issue to continue this discussion from the PR and track the resolution.

**Comment by mchitre** [comment]
Investigated this further. Performance of OS X VM seems to be really really bad, seeing network delays of more than 5 seconds when the CPU is loaded!

We could drop tests that involve load, and this will be resolved, but then we won't be testing system under load (which frequently leads to uncovering bugs). Alternatively we could drop load tests only on OS X. Thoughts?

**Comment by notthetup** [comment]
Yup. We usually test on OSX on our laptops. So I'm OK with dropping OS X tests from the CI.

**Comment by mchitre** [comment]
Done. Let's see how it goes...
