### ISSUE TITLE
Add response to auth request over JSON API

### ISSUE THREAD

**Issue by mchitre** [org-arl/fjage#164]
Add a JSON response to the `{"action": "auth"}` message to provide feedback on whether the auth was successful or not. Optionally, provide a feedback each time a JSON message is ignored because the connection is not authenticated.

@notthetup does this meet the application demand we discussed today?

**Comment by notthetup** [comment]
Yes. That would meet the application need.

**Comment by mchitre** [comment]
Done

**Comment by notthetup** [comment]
@mchitre https://github.com/org-arl/fjage/commit/ae630b42822a3240ec1d1380125a23538bbc8ac0 this commit doesn't seem to have been merged into `dev`

**Comment by mchitre** [comment]
Merged to `dev`

**Comment by mchitre** [comment]
Do note a slight change to the response message to include details of what action failed.
