### ISSUE TITLE
API documentation link seems to be broken

### ISSUE THREAD

**Issue by prasadtiru** [org-arl/fjage#207]
For example, click on the following link:

https://org-arl.github.com/fjage/javadoc/index.html?org/arl/fjage/TickerBehavior.html

**Comment by mchitre** [comment]
Where did you find this link?

**Comment by prasadtiru** [comment]
We can visit this link https://fjage.readthedocs.io/en/latest/ on fjage documentation and scroll down to look at `fjåge API documentation` link, clicking on which brings us to https://org-arl.github.com/fjage/javadoc/ which seems to be broken.

**Comment by mchitre** [comment]
Fixed.
