### ISSUE TITLE
Setting float arrays using fjage C API 

### ISSUE THREAD

**Issue by prasadtiru** [org-arl/fjage#210]
Currently `fjage_msg_add_float_array()` function is used to set array values in a message. This function does base64 encoding of the array. However, the base64 encoding in the JSON message might be incorrect. Here is an example when trying to set `node.location`:

The array is base64 encoded in the JSON message that is sent when we set `node.location` using fjage C APIs shown here:
```
{
   "action":"send",
   "relay":true,
   "message":{
      "clazz":"org.arl.fjage.param.ParameterReq",
      "data":{
         "msgID":"hpx3MLYv/yzMtIQeIbtPvxxAfXyTe0ExbUWo",
         "perf":"REQUEST",
         "recipient":"node",
         "sender":"CGatewayAgent@000041a7",
         "index":-1,
         "param":"location",
         "value":"AACAPwAAAEAAAEBA"
      }
   }
}
```
whereas, if I use a groovy shell remotely to set `node.location` (this works as expected), the JSON message that is sent is
```
{
   "id":"94b9ea5d-c3bd-4f87-a6fd-6a77665fe075",
   "action":"send",
   "message":{
      "clazz":"org.arl.fjage.param.ParameterReq",
      "data":{
         "index":-1,
         "requests":null,
         "param":"location",
         "value":[
            1.0,
            2.0,
            3.0
         ],
         "msgID":"94b9ea5d-c3bd-4f87-a6fd-6a77665fe075",
         "perf":"REQUEST",
         "recipient":"node",
         "sender":"unetsh#-b7yprc",
         "inReplyTo":null,
         "sentAt":1623986170855
      }
   },
   "relay":true
}
```

**Comment by mchitre** [comment]
The encoding was not incorrect, as we do allow bare base64 array encoding in the specifications (although we configure the Java end to always include class information).

Added 2 fixes to improve compatibility though:
bbb369133e0562ffc12938467f447c57e1ddafbd -- to handle non-b64 encoded arrays in C gateway (was a bug)
c6a3b8d3171ef1c86f558d842b26985ab7c1678a -- to include clazz information in b64 encoded arrays from C gateway (enhancement)
