### ISSUE TITLE
buildjs task seems to rebuild when nothing has changed

### ISSUE THREAD

**Issue by mchitre** [org-arl/fjage#221]
`buildjs` task seems to need to rebuild at every call to `gradle`, and it takes time. This makes development & testing very painful.

**Comment by notthetup** [comment]
Will investigate and see if it can be sped up.

**Comment by notthetup** [comment]
OK I guess we can use gradle for this..

https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:up_to_date_checks

**Comment by notthetup** [comment]
49f091e should fix this.
