### ISSUE TITLE
Connection-based firewall

### ISSUE THREAD

**Issue by ngyewch** [org-arl/fjage#222]
`org.arl.fjage.auth.AbstractFirewall` does not seem to take multiple connections (with different credentials) into account. The `auth ` flag in the code essentially behaves as a global variable. Playing around with this seems to show this behaviour. I might be using this wrong though.

I've made something that addresses this issue: https://github.com/ngyewch/fjage-extras/tree/main/fjage-security

**Comment by mchitre** [comment]
@ngyewch you're right that although each `ConnectionHandler` supports a different firewall instance, the current very simple implementation indeed gives the same `fw` object to each `ConnectionHandler`.

Your solution of using a thread-local session will solve the problem and will work. However, it assumes a single thread per connector, and this could turn out to be brittle in longer term if we ever have multi-threaded connectors. I can think of two solutions:
1. Pass the connector as a parameter to `permit()`, allowing it to make decisions based no connector instance.
2. Have a `fw` per connection and use a factory method to create a new `fw` each time a connection is opened.

Preferences or thoughts on this?

**Comment by ngyewch** [comment]
> Your solution of using a thread-local session will solve the problem and will work. However, it assumes a single thread per connector, and this could turn out to be brittle in longer term if we ever have multi-threaded connectors.

Agreed. It's a hack for something I needed to implement for use by a 3rd-party (they're not directly using the firewall, just connecting to the `MasterContainer`). 

> 1. Pass the connector as a parameter to permit(), allowing it to make decisions based no connector instance.

From a pure design standpoint, `Firewall` should not need access to `Connector`.

> 2. Have a fw per connection and use a factory method to create a new fw each time a connection is opened.

This probably makes more sense.

```
public interface FirewallFactory {
    Firewall newFirewall();
}
```

```
MasterContainer(Platform platform, int port, FirewallFactory fwFactory)
```

In this case `Firewall.authenticate()` shouldn't require a `Connector` parameter (ideally), but this can't happen because of backward-compatibility.

**Comment by mchitre** [comment]
We can rework the firewall API, as the API isn't used much anywhere yet and can be considered experimental. Better to get the design right now, than to hack around later.
