### ISSUE TITLE
`ps` implicitly assumes all agents respond to `ParameterReq`

### ISSUE THREAD

**Issue by mchitre** [org-arl/fjage#230]
Recently introduced class names for remote agents implicitly assumes all agents respond to `ParameterReq` for parameter `type`. This is a poor assumption and should be removed.

Suggested fix:
- Update fjåge JSON protocol to optionally include classname in `"action": "agents"` response.
- Display info on whether the agent is remote or local in the display

**Comment by mchitre** [comment]
Fixed.

Currently adds a `[R]` tag at the end of the `ps` entry for remote agents. Example:
```
unity: org.arl.unet.diversity.Unity
mac: org.arl.unet.mac.CSMA
bb: org.arl.unet.bb.Baseband [R]
phy: org.arl.unet.phy.Physical [R]
```

Other possible styles:

VERBOSE:
```
unity: org.arl.unet.diversity.Unity
mac: org.arl.unet.mac.CSMA
bb: org.arl.unet.bb.Baseband [REMOTE]
phy: org.arl.unet.phy.Physical [REMOTE]
```

DISCRETE:
```
unity: org.arl.unet.diversity.Unity
mac: org.arl.unet.mac.CSMA
bb: org.arl.unet.bb.Baseband*
phy: org.arl.unet.phy.Physical*
```

@notthetup Preferences? Alternative suggestions?

**Comment by notthetup** [comment]
Ooops. I prefer the VERBOSE style.

**Comment by mchitre** [comment]
Changed to `[REMOTE]`
