### ISSUE TITLE
[doc] quickstart link now gets redirected to another link by GitHub

### ISSUE THREAD

**Issue by rohitbhatnagar85** [org-arl/fjage#24]
Quickstart link https://raw.github.com/org-arl/fjage/master/src/sphinx/fjage_quickstart.sh now gets redirected to https://raw.githubusercontent.com/org-arl/fjage/master/src/sphinx/fjage_quickstart.sh

```curl```  command needs to be changed with either of following in documentation:

``` groovy
curl -O https://raw.githubusercontent.com/org-arl/fjage/master/src/sphinx/fjage_quickstart.sh
```
or
```groovy 
curl -LOR http://search.maven.org/remotecontent?filepath=com/github/org-arl/fjage/$VERSION/fjage-$VERSION.jar
```

Also the links inside the script ```fjage_quickstart.sh```  should also be fixed accordingly.

**Comment by mchitre** [comment]
Fixed in commit e576c72dbe.
