### ISSUE TITLE
[WebShell] provision for automatic port selection and port number query

### ISSUE THREAD

**Issue by rohitbhatnagar85** [org-arl/fjage#25]
When the ```WebShell``` is configured to run ``` WebServer``` with automatic port selection, it would be useful to have the port number exposed, which can be queried by the applications.

**Comment by mchitre** [comment]
Added support in 42b3fe7a0a0.  Untested.  Please test.

**Comment by rohitbhatnagar85** [comment]
Thanks @mchitre the fix works as requested. But as the assigned port can be queried only after the startup of platform, and other agents may not have the reference of WebShell available with them. Can we expose the ```Shell``` from the ```ShellAgent``` so that we can query it easily.
```
container.getAgent(agent("shell2")).getShell().getPort()
```
Should I add the getter in ```ShellAgent```?

**Comment by mchitre** [comment]
No can do.  The ```ShellAgent``` knows nothing about web servers, as that is the job of the ```WebShell```.  So it would not be right to have a ```getPort()``` method on the ```ShellAgent```.

**Comment by rohitbhatnagar85** [comment]
but can it have a method ```getShell()``` which will return the shell (which can be of any type)

**Comment by mchitre** [comment]
Ah, now I understand your question.  Yes, that should be fine.

**Comment by rohitbhatnagar85** [comment]
So basically we can query ```ShellAgent``` for the ```Shell``` and the application can figure out which shell it is looking for based on the underlying class type.

**Comment by mchitre** [comment]
Yes, that is fine.  Or if the application created the shell in the first place, it will know.

**Comment by mchitre** [comment]
Method ```getShell()``` added in 3d5127111328eca35f86d8a2b1d7030d10bdcaba.
