### ISSUE TITLE
fjagepy 1.7.2 -> 1.7.3 upgrade broken

### ISSUE THREAD

**Issue by impala454** [org-arl/fjage#268]
Hey guys, we just got the upgrade to fjagepy from 1.7.2 to 1.7.3 and are met with dependency errors on Ubuntu 20.04.  This was in an automated nightly docker build which ran with:

    cd /third_party_libs && \
        git clone https://github.com/org-arl/unet-contrib.git && \
        cd unet-contrib/unetsocket/python && \
        pip3 install . && \

output:

    #22 540.8 Cloning into 'unet-contrib'...
    #22 555.6 Processing /third_party_libs/unet-contrib/unetsocket/python
    #22 559.8 Collecting fjagepy>=1.7.2
    #22 560.0   Downloading fjagepy-1.7.3.tar.gz (14 kB)
    #22 562.5     ERROR: Command errored out with exit status 1:
    #22 562.5      command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ei2ln3vj/fjagepy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ei2ln3vj/fjagepy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-ei2ln3vj/fjagepy/pip-egg-info
    #22 562.5          cwd: /tmp/pip-install-ei2ln3vj/fjagepy/
    #22 562.5     Complete output (5 lines):
    #22 562.5     Traceback (most recent call last):
    #22 562.5       File "<string>", line 1, in <module>
    #22 562.5       File "/tmp/pip-install-ei2ln3vj/fjagepy/setup.py", line 3, in <module>
    #22 562.5         with open('../../src/sphinx/pythongw.rst') as f:
    #22 562.5     FileNotFoundError: [Errno 2] No such file or directory: '../../src/sphinx/pythongw.rst'

Testing upgrade from an already built image:

    ✔ ] # pip show fjagepy
    Name: fjagepy
    Version: 1.7.2
    Summary: Python Gateway
    Home-page: https://github.com/org-arl/fjage/tree/master/gateways/python
    Author: Prasad Anjangi, Mandar Chitre, Chinmay Pendharkar, Manu Ignatius
    Author-email: prasad@subnero.com, mandar@arl.nus.edu.sg, chinmay@subnero.com, manu@subnero.com
    License: BSD (3-clause)
    Location: /usr/local/lib/python3.8/dist-packages
    Requires: numpy
    Required-by: unetpy

pip upgrade:

    ✔] # pip install -U fjagepy
    Collecting fjagepy
      Downloading fjagepy-1.7.3.tar.gz (14 kB)
        ERROR: Command errored out with exit status 1:
         command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-wpfx56t5/fjagepy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-wpfx56t5/fjagepy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-wpfx56t5/fjagepy/pip-egg-info
             cwd: /tmp/pip-install-wpfx56t5/fjagepy/
        Complete output (5 lines):
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-install-wpfx56t5/fjagepy/setup.py", line 3, in <module>
            with open('../../src/sphinx/pythongw.rst') as f:
        FileNotFoundError: [Errno 2] No such file or directory: '../../src/sphinx/pythongw.rst'
        ----------------------------------------
    ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by notthetup** [comment]
Thanks. Fixed in 1.7.4 release : https://pypi.org/project/fjagepy/

https://github.com/org-arl/fjage/pull/269
