### ISSUE TITLE
Better error reporting for spelling errors in fjage shell

### ISSUE THREAD

**Issue by manuignatius** [org-arl/fjage#28]
Print better error messages for spelling exceptions (see the screenshot)

<img width="847" alt="screen shot 2016-02-02 at 11 57 40 am" src="https://cloud.githubusercontent.com/assets/4144181/12739597/f133bb1e-c9a5-11e5-9677-6bb13cda577a.png">

**Comment by mchitre** [comment]
Better?

<img width="399" alt="image" src="https://user-images.githubusercontent.com/3949878/62615529-0554cd80-b940-11e9-9110-70107cfb572f.png">
