### ISSUE TITLE
Update quick start guide to support non-PowerShell usecase

### ISSUE THREAD

**Issue by notthetup** [org-arl/fjage#29]
The windows section of the [Quick Start guide](https://org-arl.github.io/fjage/doc/html/quickstart.html) uses [a power shell script](https://raw.githubusercontent.com/org-arl/fjage/master/src/sphinx/fjage_quickstart.ps1) to download the relevant jars and and create a `.bat` file. 

While makes for a great solution for *nix systems to allow a single command install, it would be more common for windows users to not have powershell installed.

Instead a ziped folder with the required jars and a pre generated batch file (of the following format) could be provided for download. Then the quick start shell can be launched by just double clicking the `.bat` file.

```
@echo off
set CLASSPATH=build\libs\commons-lang3-3.1.jar;build\libs\fjage-1.3.4.jar;build\libs\groovy-all-2.4.4.jar;build\libs\jline-2.12.jar;samples
set GUI=false
java -Dfjage.gui=false org.arl.fjage.shell.GroovyBoot etc\initrc.groovy
```

**Comment by mchitre** [comment]
@notthetup : Would you be open to fixing this sometime? Perhaps not for the upcoming release, but sometime down the road?

**Comment by notthetup** [comment]
Yes. I this is on my radar. You can assign it to me.

**Comment by mchitre** [comment]
We have decided to discontinue quickstart for PowerShell
