### ISSUE TITLE
History doesn't come in web shell using up key

### ISSUE THREAD

**Issue by rohitbhatnagar85** [org-arl/fjage#30]
<img width="832" alt="screen shot 2016-03-01 at 8 28 34 pm" src="https://cloud.githubusercontent.com/assets/1551764/13430766/5c947bc6-dfec-11e5-8a5a-d01d41d0560f.png">

**Comment by mchitre** [comment]
@rohitbhatnagar85 : Do you plan to fix this for the upcoming release?

**Comment by rohitbhatnagar85** [comment]
@mchitre: Yes planning to debug this soon. will request for help if stuck anywhere.

**Comment by rohitbhatnagar85** [comment]
The issue was happening only in Chrome and was working fine in Safari browser. 
Looks like there is a global Javascript variable named ```history``` already defined and was causing the clash with our command history variable. Renaming it solved the problem.

**Comment by notthetup** [comment]
Yup. `window.history` is used by the [history API](https://developer.mozilla.org/en-US/docs/Web/API/History_API)
