### ISSUE TITLE
setCommand logic in ShellExecReq class

### ISSUE THREAD

**Issue by manuignatius** [org-arl/fjage#33]
In ShellExecReq class, setter logic for cmd & script seems wrong.

Instead of : 

```
 public void setCommand(String cmd) {
    if (cmd != null && script != null) throw new UnsupportedOperationException("ShellExecReq can either have a command or script, but not both");
    this.cmd = cmd;
  }
```

may be use :

```
 public void setCommand(String cmd) {
    if (script != null) throw new UnsupportedOperationException("ShellExecReq can either have a command or script, but not both");
    this.cmd = cmd;
  }
```

as the first one will not raise an exception when cmd = null and script != null - which is the case when the setter method is first invoked.

**Comment by mchitre** [comment]
I can't see why the logic is wrong, perhaps you can think through again and explain....
