### ISSUE TITLE
Fjage Gateway in Python

### ISSUE THREAD

**Issue by notthetup** [org-arl/fjage#34]
We are adding python gateway support for `fjage`. WIP on this branch https://github.com/org-arl/fjage/tree/python.

The following tasks need to completed for this effort:

- [x] Python Shell Integration
- [x] Test
- [x] Documentation
- [x] Packaging and Publishing

** Python Shell Integration **

There is a need to integrate a python shell into the fjage gateway python port. This shell when run, should enable quick generation and sending of messages from a REPL/CLI.

For eg. : 

```
In [1]: g1 = fjage.remote.Gateway('localhost', 5081, "PythonGW")
m1 = fjage.Message()
g1.send(m1)
```

**Tests**

We should add tests akin to `BasicTests` and `AlohaTest` on the Python side of things as well. Code can be found here https://github.com/org-arl/fjage/tree/python/src/test.

We might not be able to implement all the tests (since currently the Python support is only for the Gateway functionality), but we should test what we can.

We might need to create a new `initrc_python_tests.groovy` to run a testing instance of `fjage` to run the python tests against.

** Documentation **

The sphinx documentation generation system should be extended to generate both API documentation and "User Guide" for the Python Gateway implementation.

** Packaging and Publishing

Package and publish the python `fjage` port to [pypy](https://pypy.org/). https://github.com/org-arl/arlpy is a great reference on how to setup a project to publish to pypy.

**Comment by notthetup** [comment]
Commit 654333dcb adds iPython shell with `fjage.py`

**Comment by mchitre** [comment]
Releasing in v1.4.1
