### ISSUE TITLE
Method to get the agent id running using Gateway class

### ISSUE THREAD

**Issue by prasadtiru** [org-arl/fjage#37]
Added the following piece of code in `Gateway.java` and tested. Works fine. I'm not sure if documentation is up to the mark. So prof @mchitre can perhaps improve it and suggest any changes before committing. 

```
  /**
   * Returns the gateway AgentID.
   */
  public AgentID getGWAgentID() {
    return agent.getAgentID();
  }
```

**Comment by mchitre** [comment]
Added `getAgentID()` method to `Gateway` class in commit e34c74fc4561480656a7ce7ef9d17af212846934
