### ISSUE TITLE
Improve fjåge test cases

### ISSUE THREAD

**Issue by mchitre** [org-arl/fjage#50]
- [x] Replace use of heuristic delays in fjåge test cases by deterministic logic
- [x] Add test cases for new functionality (e.g. fjågejs)
- [x] Automate testing (CI)

**Comment by notthetup** [comment]
I've been playing with integrating tests for fjågejs into gradle. It's on this branch for now. https://github.com/notthetup/fjage/tree/jasmine

https://github.com/jasmine/jasmine#installation is a nice little web test framework for running JS tests.  

I'm trying to setup the gradle tests such that it only passes when it receives a fjage message from fjågejs thata the test has passed (https://github.com/notthetup/fjage/commit/d45360b59eaa1195af080b70daa1f9db7ef5e781)

With this in place we can add normal test suites to Jasmine. But for now, someone will have to open the URL in the browser to run the jasmine tests. We can automate this using something like https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md

**Comment by mchitre** [comment]
Added test cases for `ShellAgent`

**Comment by notthetup** [comment]
Moved over the Jasmine implementation to this repo https://github.com/org-arl/fjage/tree/jasmine. Also added support for automation using https://github.com/GoogleChrome/puppeteer/

Pending writing the actual JS tests.
