### ISSUE TITLE
WebShell doesn't show a prompt on refresh

### ISSUE THREAD

**Issue by notthetup** [org-arl/fjage#58]
The new WebShell based on fjage 1.5+ doesn't show a prompt on load. If unet is already running and a new web page is loaded with the shell, it doesn't show a prompt (>) until a user presses ^C or Enter.

However, encouraging a user to press ^C or Enter is dangerous since multiple users can be connected to the same instance of unet and will have a shared/synchronized web interface.

Ideally, when a new connection is established, the Terminal should redraw the last line on each connection including the newest connection.

**Comment by mchitre** [comment]
Fixed. @notthetup see if this is what you had in mind, and if so, close this.
