### ISSUE TITLE
Shell eats up "\"

### ISSUE THREAD

**Issue by mchitre** [org-arl/fjage#60]
The shell eats up "\" characters, so we have to type "\\" to get a "\". The reason for this is that `jline:3.9.0` is broken. This bug was reported (https://github.com/jline/jline3/issues/296) and fixed in 
https://github.com/jline/jline3/commit/5a58d01c960c0800f37a85fb4baf666ab693bfdb, but this is not in a stable release yet.

We will fix when jline releases new version.

**Comment by notthetup** [comment]
Checking with jline when the next release is planned. https://github.com/jline/jline3/issues/343a

**Comment by notthetup** [comment]
JLine 3.10.0 has been released on 2019-02-12
