### ISSUE TITLE
hterm does not always show on screen keyboard on touchscreen devices

### ISSUE THREAD

**Issue by mchitre** [org-arl/fjage#64]

**Comment by notthetup** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=402972

**Comment by notthetup** [comment]
Another potential option is to migrate to something like https://xtermjs.org/

**Comment by mchitre** [comment]
Looks reasonable, but we won't know the quirks until we try it. Maybe we should be an internal test version with this replacing hterm to test run?
