### ISSUE TITLE
Enable option in WebServer to bind to localhost only

### ISSUE THREAD

**Issue by notthetup** [org-arl/fjage#74]
Enable a new option in the `WebSever` constructor to only bind to `localhost`.

This constructor variant of Jetty Server can be used 👍 

`new Server(InetSocketAddress.createUnresolved("127.0.0.1", port))`

**Comment by mchitre** [comment]
Implemented in 9e13fa9e095d55d75d68fd28430c88447b393e03

**Comment by mchitre** [comment]
@notthetup can you test this with UnetSim and close both issues if working?

**Comment by notthetup** [comment]
Tested.
