### ISSUE TITLE
Add support for search on help documentation.

### ISSUE THREAD

**Issue by notthetup** [org-arl/fjage#91]
Proposed syntax:  

`help <syntax>`

If `<syntax>` doesn't match any of the knowns help documentation topics, then it should list a bunch of possible topics.

**Comment by mchitre** [comment]
Already done in fjåge 1.6.1 (https://github.com/org-arl/fjage/commit/4a16b8b3f897d85c729df51f4d1de30576452430). Will automatically come to UnetStack when we bump up fjåge.
