### ISSUE TITLE
re-subscriptions and un-subscriptions need not be critical warnings

### ISSUE THREAD

**Issue by prasadtiru** [org-arl/fjage#92]
Should re-subscriptions or un-subscriptions from topics not subscribed to be considered critical warnings??

            ```if new_topic.name in self.subscriptions:
                self.logger.critical("Warning: Already subscribed to topic")```

```try:
                self.subscriptions.remove(new_topic.name)
            except:
                self.logger.critical("Exception: No such topic subscribed: " + new_topic.name)
```
Also we might want to update the micro-copy to call all `logger.warnings` as "Warning: " and all `logger.critical` as `Exception`. Or something consistent.

**Comment by mchitre** [comment]
Absolutely not! They don't cause anything critical!!! They should be silently ignored, or at best, logged at debug level.

**Comment by prasadtiru** [comment]
Cleaned up log messages for improved readability. For re-subscription, logging as debug, whereas for subscribing to an agent that does not exist, I am still providing a critical warning. Let me know otherwise. Fixed in 878024438e3e7392a050520f27338885d87cb721

**Comment by notthetup** [comment]
8780244

**Comment by notthetup** [comment]
What about the situation where we're trying to `unsubscribe` to a topic which isn't subscribed to. It'll currently do a `self.logger.critical("Exception: No such topic subscribed: " + new_topic.name)`

**Comment by prasadtiru** [comment]
Phrased it wrongly in the earlier comment. I meant we provide critical warning in such case where we are trying to unsubscribe a topic which isn't subscribed to. 

Just checked the behavior in java, and it silently ignores in such cases. I can do the same if it is fine.

**Comment by mchitre** [comment]
Yes, please. Silently ignore.
