### ISSUE TITLE
Size limit for PutFileReq from WebSockets

### ISSUE THREAD

**Issue by notthetup** [org-arl/fjage#98]
I built a little test to send a series of `PutFileReq` increasing in size from javascript using `fjage.js`.

It seems, there is a limit to how large a file (or an array) that the WebSocket request underneath `PutFileReq` can successfully send across. Any larger and it just seems to take forever to send. For smaller file sizes there is a trend that is followed, but after a limit, the time taken is much larger.

Even with a very very large timeout, Java wouldn't receive the array. It feels like something is caching the data and the data only gets flushed when the page is closed/reloaded or the browser.

The size at which this breaks down is dependent on the browser.

Chrome : ~50MB
Firefox : ~50MB
Safari : ~2MB

The actual time taken was...

```
kB                    seconds
10		0.011869999987538904
20		0.013799999956972897
50		0.030580000020563602
70		0.04590000002644956
100		0.06926499999826774
200		0.11515999998664483
500		0.3453800000133924
700		0.40781999996397644
1000		0.6087550000520423
2000		1.330774999980349
5000		3.2484800000092946
7000		4.320984999998473
10000		6.50650499999756
20000		12.768404999980703
50000		??
```

This was all tested on MacOS Mojave.

Looking around it seems most frontend libraries doing large transfer from browser tend to break up the file in chunks, this would help with reducing memory overhead in the browser, only load a 1MB chunk into RAM and send it instead of loading the while 50MB, and also get a handle of the progress. Potentially retries could be added in cases of errors etc.

For this though, we would need support on the `ShellAgent` side to be able to write to a file from an offset. So to add an `offset` field in PutFileReq.

[test.html.zip](https://github.com/org-arl/fjage/files/3812859/test.html.zip)

**Comment by notthetup** [comment]
Related to https://github.com/org-arl/fjage/issues/83.

**Comment by mchitre** [comment]
Okay, let's go with being able to write in chunks. We can add an offset, or we can add an append option.

**Comment by mchitre** [comment]
Tracked in #83, so closing this as duplicate.
